{
  inputs,
  ...
}:
{
  imports = [
    ./boot.nix
    ./flatpak.nix
    ./fonts.nix
    ./hardware.nix
    ./network.nix
    ./nfs.nix
    ./nh.nix
    ./quickshell.nix
    ./packages.nix
    ./printing.nix
    ./ly.nix
    ./security.nix
    ./services.nix
    ./steam.nix
    ./stylix.nix
    ./syncthing.nix
    ./system.nix
    ./thunar.nix
    ./user.nix
    ./virtualisation.nix
    ./xserver.nix
    ./vlc.nix
    ./pipewire.nix
    inputs.stylix.nixosModules.stylix
  ];
}
